# Generated by Django 5.0.1 on 2024-01-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text_color', models.CharField(max_length=50)),
                ('background_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('publish_date', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('categories', models.ManyToManyField(to='blogs.category')),
            ],
        ),
    ]
